### ISSUE TITLE
update A-Frame lib

### ISSUE THREAD

**Issue by evdem** [SBUtltmedia/aframe-glmol-component#1]
Please update your application for the latest A-Frame lib. 
I can't get accurate VR mode with the 0.8.2 release.
Your sample fails to download "http" file from PubChem with the 1.0.4 A-Frame release.

**Comment by SBUtltmedia** [comment]
Updated as requested. Please let us know if there are further problems

**Comment by evdem** [comment]
Hi,

Thank you for your letter and glmol port.
1. https://unpkg.com/aframe-glmol-component/dist/aframe-glmol-
component.min.js
"Cannot find package aframe-glmol-component@latest"
Therefore I just put your dist to my site https://www.ibiblio.org/e-
notes/webxr/samples.htm.

2. Unfortunately, with the new component, I can not move model by touchpad 
in Oculus Go https://www.ibiblio.org/e-notes/webxr/aframe-glmol.htm

it works with the old component and aframe 0.8.2 https://www.ibiblio.org/e-
notes/webxr/aframe-glmol-old.htm

3. "thickRibbon" is not accurate (maybe wrong triangle face orientation and 
face culling) but "ribbon" is good.

I'll try to make model rotation (by camera movement) in a while.

Evgeny Demidov


On Thu, 20 Feb 2020 09:15:26 -0800, TLT Media Lab wrote

**Comment by pstdenis** [comment]
1. I created a npm account which should now allow the unpkg CDN to work
2. I don't have an oculus go to test, if you create a simple a-box can you
move that in aframe 1.0.5 in oculus go?
3. Attempted fix in thick ribbon, I think it looks better now?

**Comment by evdem** [comment]
On Fri, 21 Feb 2020 14:46:56 -0800, AlmondBread wrote
> 1. I created a npm account which should now allow the unpkg CDN to 
> work
thank you

> 2. I don't have an oculus go to test, if you create a simple a-box 
> can you move that in aframe 1.0.5 in oculus go?
it works on Oculus with 1.0.0 only (it works on VR BOX2 + joystick). I made 
an A-Frame issue.

Can't make accurate controls (rotations) yet. But now one can "walk" around 
a model. It is necessary to rotate head (but it is useful for health :)

What do you use for tests Cardboard? I can try to add rotation on the 
pressed Cardboard button. Don't know how to fight HW fragmentization (e.g. 
Oculus Quest :)

> 3. Attempted fix in thick ribbon, I think it looks better now?
Yes, it is better (no holes) but moving ribbons are blinking. Just move your 
head in VR (tested in the Oculus browser). But in 2D mode all is fine 
(tested in Chrome). I'll make more tests.

Thank you for the fast response AlmondBread. Isn't it yours :)
https://www.ibiblio.org/e-notes/MSet/TheAlmondBreadHomepage.htm

Evgeny

**Comment by evdem** [comment]
thick ribbons are blinking in not-VR mode too. Just move the model closely by 
the up arrow and rotate it by mouse. I think it is just illumination feature. 
Maybe use more accurate ribbons (more triangles)?

**Comment by evdem** [comment]
forgot again: don't you have really big molecule models. E.g. proteins and so 
on to see depth in VR and to test performance?

**Comment by evdem** [comment]
you can compare ribbons at https://www.ibiblio.org/e-notes/webgl/chem/pdb.html 
ChemDoodle Web Component library models.
